export const COUNCIL_CAST_ORDER = ['Conductor', 'Strategist', 'Architect', 'Decomposer'];

export const ORCHESTRATION_FLOW_STEPS = [
  {
    id: 'intake',
    label: '안건 접수',
    owner: '운영자 · 안건 흐름',
    surface: 'mission',
    summary: '현재 안건 판단과 다음 이동을 시작합니다.',
  },
  {
    id: 'council',
    label: '참모 회의',
    owner: '회의 리드 + 참여 역할',
    surface: 'council',
    summary: '각 역할이 같은 안건을 함께 읽고 방향을 정리합니다.',
  },
  {
    id: 'execution',
    label: '작업 지시',
    owner: '실행 역할 · 실행 흐름',
    surface: 'execution',
    summary: '현재 작업 지시와 다음 실행을 정리합니다.',
  },
  {
    id: 'deliverables',
    label: '결과 보고',
    owner: '결과 보고 · 보고 흐름',
    surface: 'deliverables',
    summary: '현재 보고 판단과 다음 행동을 확인합니다.',
  },
];

export const ORCHESTRATION_RULES = [
  '프로젝트 지정 후 실행',
  '리뷰 후 완료',
  '승인 후 커밋',
  '한정된 실행 유지',
];

export const COUNCIL_CAST_METADATA = {
  Conductor: {
    archetype: '정렬 책임',
    avatarLabel: '리드 아바타',
    avatarMood: '중앙 판단판을 보며 최종 방향을 고정합니다.',
    avatarStyle: 'lead',
    commandLine: '현재 결론과 다음 인계 판단을 한 지점에서 정리합니다.',
    deskLabel: '중앙 판단 데스크',
    deskProp: '최종 판단판 · 승인 묶음',
    displayName: '리드',
    mark: 'CN',
    officeLine: '최종 방향과 인계 승인을 보는 자리',
    orderLabel: '역할 순서 1',
    previewLine: '정렬 상태와 다음 인계 판단을 한 지점에서 확인합니다.',
    rank: '회의 리드',
    tone: 'accent',
  },
  Strategist: {
    archetype: '목표 정리',
    avatarLabel: '전략 아바타',
    avatarMood: '우선순위 표와 목표 문장을 동시에 정리합니다.',
    avatarStyle: 'strategist',
    commandLine: '목표 해석과 범위 조정을 맡는 전략 역할입니다.',
    deskLabel: '전략 판단 데스크',
    deskProp: '우선순위 표 · 전략 메모',
    displayName: '전략',
    mark: 'ST',
    officeLine: '목표와 우선순위를 다듬는 자리',
    orderLabel: '역할 순서 2',
    previewLine: '원하는 결과와 범위를 더 분명하게 정리합니다.',
    rank: '전략 역할',
    tone: 'success',
  },
  Architect: {
    archetype: '경계 보호',
    avatarLabel: '설계 아바타',
    avatarMood: '경계 도면을 펼친 채 파급 범위를 봉인합니다.',
    avatarStyle: 'architect',
    commandLine: '설계 파급을 줄이고 시스템 경계를 지키는 역할입니다.',
    deskLabel: '설계 검토 데스크',
    deskProp: '경계 도면 · 구조 메모',
    displayName: '설계',
    mark: 'AR',
    officeLine: '구조 리스크와 경계를 지키는 자리',
    orderLabel: '역할 순서 3',
    previewLine: '의미론 경계를 지키고 파급 범위를 작게 유지합니다.',
    rank: '설계 역할',
    tone: 'warning',
  },
  Decomposer: {
    archetype: '첫 실행 단위',
    avatarLabel: '실행 아바타',
    avatarMood: '첫 실행 셀과 체크포인트를 짧게 편성합니다.',
    avatarStyle: 'decomposer',
    commandLine: '첫 실행 단위를 정리하고 바로 인계 가능한 수준으로 나눕니다.',
    deskLabel: '실행 편성 데스크',
    deskProp: '체크포인트 표 · 실행 큐',
    displayName: '실행',
    mark: 'DC',
    officeLine: '첫 실행 셀과 체크포인트를 편성하는 자리',
    orderLabel: '역할 순서 4',
    previewLine: '의도를 바로 넘길 수 있는 첫 실행 단위로 나눕니다.',
    rank: '실행 역할',
    tone: 'neutral',
  },
};
